### ISSUE TITLE
 gcc: error: unrecognized command line option ‘-stdlib=libc++’ error: command '/usr/bin/gcc' failed with exit code 1

### ISSUE THREAD

**Issue by winerholiday** [yipihey/FastCDF#1]
Hi! Your code helps me a lot! However, I am a newcomer in the field of C++. When I run

` python -m setup.py install`

It truns out that

` EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning, gcc: error: unrecognized command line option ‘-stdlib=libc++’
  error: command '/usr/bin/gcc' failed with exit code 1`

I do not know what to do.Thank you

**Comment by yipihey** [comment]
You may want to modify the line 
`cpp_args = ['-std=c++11', '-stdlib=libc++', '-I/usr/local/include/eigen3']`
in setup.py

E.g. try `-stdlib=libstdc++` which may be what your gcc installation needs. 
It all depends on what local c compiler you have. 
Good luck!

**Comment by winerholiday** [comment]
It works！ Thank you！
